version: "3.7"
services:
  simulator:
    build: .

    ports:
      #### Web UI (noVNC)
      - "8080:8080"

      #### Universal Robots simulator
      - "502:502" # Modbus Port
      - "29999:29999" # Dashboard Server Interface Port
      - "30001:30001" # Primary Interface Port
      - "30002:30002" # Secondary Interface Port
      - "30003:30003" # Real-time Interface Port
      - "30004:30004" # RTDE Interface Port

    environment:
      - RESOLUTION=1280x800
      # Supported models: UR3, UR5, UR10 (will be used by default), UR16.
      - ROBOT_MODEL=UR10
